version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/nginx/config:/etc/nginx
      - /opt/docker/nginx/certs:/etc/ssl/private
      - /opt/docker/nginx/logs:/var/log/nginx
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy