version: "3.8"
name: portainer
services:
  agent:
    container_name: core.portainer.agent
    image: portainer/agent:2.19.4
    restart: always
    ports:
    # Only for 10.255.0.2:9001 not 0.0.0.0:9001
      - "10.255.0.2:9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer

networks:
  portainer:
    external: false
    name: portainer